### ISSUE TITLE
Dual mode - local and Tuya cloud

### ISSUE THREAD

**Issue by JFox-sk** [banksy-git/lidl-gateway-freedom#18]
Hi,
when I hack the Gateway using these scipts, can I still using Tuya mobile app (aka dual mode: local + tuya cloud)? 
Thank you!

**Comment by JFox-sk** [comment]
So, I tried it, and the answer is - no, I can not use both modes at the same time, but I can easily switch between the modes.

**Comment by MattWestb** [comment]
I think (= not knowing) its only renaming the start script and copy the original back and its starting tuya app.

Perhaps tuya is updating the box and you is loosing the hacked start script but  the root password shall being OK.

Also it can being that tuya app is not liking the updated Zigbee firmware.

Great that you have testing it !!

**Comment by JFox-sk** [comment]
Yes @MattWestb just rename the start script (or change symbolic link).

**Comment by MattWestb** [comment]
Did you upgrading the firmware on the Zigbee module ?
And is yes did tuya cloud like it or downgrading it ?
I have not testing if tuya is downgrading the Zigbee module but im curious  if they is having making upgrading then LIDL and more  customer have getting new Zigbee certificate and i have not reversing my ZBGWs for testing (they is in production on my test network and sniffing Zigbee trafic).
